      -- Crear la base de datos
CREATE DATABASE IF NOT EXISTS `parcial_sis_fact`;
USE `parcial_sis_fact`;

-- Crear tabla TAMANO
CREATE TABLE IF NOT EXISTS `TAMANO` (
  `ID_TAMANO` INT AUTO_INCREMENT PRIMARY KEY,
  `DESCRIPCION` VARCHAR(50) NOT NULL,
  `ACTIVO` BOOLEAN NOT NULL DEFAULT TRUE,
  `FECHA_CREACION` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `MODIFICADO` BOOLEAN DEFAULT FALSE,
  `TAMANO_MAXIMO` DECIMAL(10,2),
  `TAMANO_MINIMO` DECIMAL(10,2),
  `UNIDAD_MEDIDA` ENUM('cm', 'm', 'in', 'ft') NOT NULL,
  `CODIGO_TAMANO` VARCHAR(20) UNIQUE,
  `CLASIFICACION` VARCHAR(50)
);

-- Crear tabla PRODUCTO
CREATE TABLE IF NOT EXISTS `PRODUCTO` (
  `ID_PRODUCTO` INT AUTO_INCREMENT PRIMARY KEY,
  `NOMBRE_PRODUCTO` VARCHAR(100) NOT NULL UNIQUE,
  `DESCRIPCION` TEXT,
  `PRECIO` DECIMAL(10,2) NOT NULL,
  `FECHA_LANZAMIENTO` DATE NOT NULL,
  `ID_TAMANO` INT,
  `ACTIVO` BOOLEAN DEFAULT TRUE,
  `STOCK` INT DEFAULT 0,
  `PROMOCION` BOOLEAN DEFAULT FALSE,
  `PESO` DECIMAL(5,2),
  FOREIGN KEY (`ID_TAMANO`) REFERENCES `TAMANO`(`ID_TAMANO`) ON DELETE CASCADE
);

-- Crear tabla CATEGORIA_DE_PRODUCTO
CREATE TABLE IF NOT EXISTS `CATEGORIA_DE_PRODUCTO` (
  `CATEGORIA_ID` INT AUTO_INCREMENT PRIMARY KEY,
  `CATEGORIA` VARCHAR(50) NOT NULL UNIQUE,
  `DESCRIPCION` TEXT,
  `ACTIVO` BOOLEAN DEFAULT TRUE,
  `FECHA_CREACION` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `CODIGO_CATEGORIA` VARCHAR(20) UNIQUE
);

-- Crear tabla COLOR
CREATE TABLE IF NOT EXISTS `COLOR` (
  `COLOR_ID` INT AUTO_INCREMENT PRIMARY KEY,
  `NOMBRE_COLOR` VARCHAR(50) NOT NULL,
  `CODIGO_COLOR` VARCHAR(7) NOT NULL,
  `ACTIVO` BOOLEAN DEFAULT TRUE,
  `DESCRIPCION` TEXT,
  `RGB_VALUE` VARCHAR(20)
);

-- Crear tabla CATEGORIAS
CREATE TABLE IF NOT EXISTS `CATEGORIAS` (
  `CATEGORIA_ID` INT AUTO_INCREMENT PRIMARY KEY,
  `NOMBRE_CATEGORIA` VARCHAR(50) NOT NULL UNIQUE,
  `ACTIVO` BOOLEAN DEFAULT TRUE,
  `DESCRIPCION` TEXT,
  `FECHA_CREACION` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `CATEGORIA_PRINCIPAL` BOOLEAN DEFAULT FALSE
);

-- Crear tabla intermedia PRODUCTO_CATEGORIA
CREATE TABLE IF NOT EXISTS `PRODUCTO_CATEGORIA` (
  `ID_PRODUCTO` INT,
  `CATEGORIA_ID` INT,
  PRIMARY KEY (`ID_PRODUCTO`, `CATEGORIA_ID`),
  FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `PRODUCTO`(`ID_PRODUCTO`) ON DELETE CASCADE,
  FOREIGN KEY (`CATEGORIA_ID`) REFERENCES `CATEGORIA_DE_PRODUCTO`(`CATEGORIA_ID`) ON DELETE CASCADE
);

-- Crear tabla intermedia PRODUCTO_COLOR
CREATE TABLE IF NOT EXISTS `PRODUCTO_COLOR` (
  `ID_PRODUCTO` INT,
  `COLOR_ID` INT,
  PRIMARY KEY (`ID_PRODUCTO`, `COLOR_ID`),
  FOREIGN KEY (`ID_PRODUCTO`) REFERENCES `PRODUCTO`(`ID_PRODUCTO`) ON DELETE CASCADE,
  FOREIGN KEY (`COLOR_ID`) REFERENCES `COLOR`(`COLOR_ID`) ON DELETE CASCADE
);

-- Insertar 10 registros en TAMANO
INSERT INTO `TAMANO` (`DESCRIPCION`, `ACTIVO`, `FECHA_CREACION`, `MODIFICADO`, `TAMANO_MAXIMO`, `TAMANO_MINIMO`, `UNIDAD_MEDIDA`, `CODIGO_TAMANO`, `CLASIFICACION`) 
VALUES 
('Pequeño', TRUE, NOW(), FALSE, 10, 1, 'cm', 'P001', 'Pequeño'),
('Mediano', TRUE, NOW(), FALSE, 50, 10, 'cm', 'M002', 'Mediano'),
('Grande', TRUE, NOW(), FALSE, 100, 51, 'cm', 'G003', 'Grande'),
('X-Large', TRUE, NOW(), FALSE, 150, 101, 'cm', 'XL004', 'X-Large'),
('XX-Large', TRUE, NOW(), FALSE, 200, 151, 'cm', 'XXL005', 'XX-Large'),
('Mini', TRUE, NOW(), FALSE, 5, 0.5, 'cm', 'MN006', 'Mini'),
('Macro', TRUE, NOW(), FALSE, 300, 201, 'cm', 'MC007', 'Macro'),
('Gigante', TRUE, NOW(), FALSE, 500, 301, 'cm', 'GG008', 'Gigante'),
('Compacto', TRUE, NOW(), FALSE, 8, 2, 'cm', 'CP009', 'Compacto'),
('Ultra', TRUE, NOW(), FALSE, 700, 501, 'cm', 'UL010', 'Ultra');

-- Insertar 10 registros en PRODUCTO
INSERT INTO `PRODUCTO` (`NOMBRE_PRODUCTO`, `DESCRIPCION`, `PRECIO`, `FECHA_LANZAMIENTO`, `ID_TAMANO`, `ACTIVO`, `STOCK`, `PROMOCION`, `PESO`) 
VALUES 
('Producto A', 'Descripción del producto A', 15.50, '2025-01-01', 1, TRUE, 50, TRUE, 2.5),
('Producto B', 'Descripción del producto B', 25.00, '2025-02-01', 2, TRUE, 30, FALSE, 1.5),
('Producto C', 'Descripción del producto C', 35.00, '2025-03-01', 3, TRUE, 20, TRUE, 3.0),
('Producto D', 'Descripción del producto D', 45.00, '2025-04-01', 4, TRUE, 40, TRUE, 2.0),
('Producto E', 'Descripción del producto E', 55.00, '2025-05-01', 5, TRUE, 10, FALSE, 4.0),
('Producto F', 'Descripción del producto F', 65.00, '2025-06-01', 6, TRUE, 15, FALSE, 1.2),
('Producto G', 'Descripción del producto G', 75.00, '2025-07-01', 7, TRUE, 25, TRUE, 2.8),
('Producto H', 'Descripción del producto H', 85.00, '2025-08-01', 8, TRUE, 12, TRUE, 3.5),
('Producto I', 'Descripción del producto I', 95.00, '2025-09-01', 9, TRUE, 22, FALSE, 1.7),
('Producto J', 'Descripción del producto J', 105.00, '2025-10-01', 10, TRUE, 18, TRUE, 4.2);

-- Consultar la estructura de todas las tablas en la base de datos
SELECT TABLE_NAME, COLUMN_NAME, COLUMN_TYPE, IS_NULLABLE, COLUMN_DEFAULT, COLUMN_KEY
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'parcial_sis_fact'
ORDER BY TABLE_NAME, ORDINAL_POSITION;
